In [1]:

import numpy as np
from sklearn import preprocessing, neighbors, svm
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:

df = pd.read_csv('data/breast-cancer-wisconsin.data.txt')
df.replace('?', -99999, inplace=True) #sees -99999 as outlier, ignores it
df.drop(['id'], 1, inplace=True) #id column seems useless, its just an id
X = np.array(df.drop(['class'],1)) #using everything except class to train
print(X)
Y = np.array(df['class']) #class is the final result obviously

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

clf = svm.SVC() # we need to use SVR for predicting
clf.fit(X_train, Y_train)

accuracy = clf.score(X_test, Y_test)
print(accuracy)

example_measures = np.array([[4,2,1,1,1,2,3,2,1],[4,2,1,2,2,2,3,2,1]])
example_measures = example_measures.reshape(len(example_measures), -1)
prediction = clf.predict(example_measures)
print(prediction)


[[5 1 1 ... 3 1 1]
 [5 4 4 ... 3 2 1]
 [3 1 1 ... 3 1 1]
 ...
 [5 10 10 ... 8 10 2]
 [4 8 6 ... 10 6 1]
 [4 8 8 ... 10 4 1]]
0.9571428571428572
[2 2]


C:\Users\Jai\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [3]:


df = pd.read_csv('data/2019 Line 280 AVL.csv')

df1 = pd.get_dummies(df, columns=['Day of Week'],prefix=['Enc_'])
df1 = df1.loc[df['Bus Stop ID'] == 775]

df.fillna(value = -9999)
enc = OneHotEncoder(handle_unknown='ignore')
df1['Actual Depart Hour'] = df['Actual Depart'].str.split(':',expand=True)[0]

# df.replace('?', -99999, inplace=True) #sees -99999 as outlier, ignores it
df1.drop(['Bus Stop ID','Transit Date', 'Vehicle #', 'Block #', 'Route #', 'Trip #', 'Direction','Pattern','Bus Stop Name', 'Stop Sequence','Latitude','Longitude','Scheduled Depart','Actual Depart','Initial Performance Result','Reported Performance Results','Actual Arrival','Waivers','Dwell Time', 'Actual Run Time', 'Scheduled Operating Speed','Actual Operating Speed','Run Time Variance','Day Type','Time Period'], 1, inplace=True) #id column seems useless, its just an id
print(df1.head)
# pd.to_numeric(df1['Actual Operating Speed'], errors='coerce')
X = np.array(df1.drop(['Difference (Minutes)'],1)) #using everything except class to train
Y = np.array(df1['Difference (Minutes)']) #class is the final result obviously
np.nan_to_num(X)
np.nan_to_num(Y)
pd.isnull(X)
np.nan_to_num(X)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

clf = svm.SVC()
clf.fit(X_train, Y_train)

accuracy = clf.score(X_test, Y_test)
print(accuracy)




<bound method NDFrame.head of         Difference (Minutes)  Scheduled Run Time  Miles from Prior Time Point  \
3                         -1                   8                        0.598   
4                         -1                   0                        6.444   
9                          0                   8                        6.444   
10                         0                   0                        0.598   
16                         1                   8                        6.444   
...                      ...                 ...                          ...   
202556                    14                   9                        6.444   
202567                     8                   9                        6.444   
202583                     2                   9                        6.444   
202594                     2                   9                        6.444   
202605                     1                   9                        6.444  

C:\Users\Jai\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.2570268582136165
